### ISSUE TITLE
Use API v3 /account endpoint

### ISSUE THREAD

**Issue by dpiddy** [heroku/heroku-bouncer#44]
With the shiny new `allow_if_user` hook #42 added I'd like to check for `two_factor_authentication` but it's not returned on the v2 `/account` endpoint.

cc @jacobian

**Comment by wuputah** [comment]
Seems okay to modify this? 
https://github.com/heroku/heroku-bouncer/blob/master/lib/heroku/bouncer/middleware.rb#L187-L193

But if the fields change significantly, it might break people's apps.

**Comment by wuputah** [comment]
AFAICT, `/account` is also the V3 endpoint, so is this a matter of setting a particular header?

**Comment by mattreduce** [comment]
@wuputah that's right—specifically the `Accept` header at https://github.com/heroku/heroku-bouncer/blob/master/lib/heroku/bouncer/middleware.rb#L194 would need to be `application/vnd.heroku+json; version=3` instead.
