### ISSUE TITLE
Rename `HEROKU_` defaults?

### ISSUE THREAD

**Issue by raul** [heroku/heroku-bouncer#47]
As reported by @maxbeizer, Bouncer encourages the usage of env vars with a `HEROKU_` prefix - should we rename these defaults? (In which case we should also modify https://github.com/heroku/omniauth-heroku).

**Comment by wuputah** [comment]
I don't feel these are in danger of being a conflict with Heroku's features. Additionally, these specific env vars are only a recommendation in the README, so the end-user may use whatever ENV vars they wish (or not use ENV vars at all).

Having bouncer pick up these ENV vars automatically is a deprecated feature and [produces a warning](https://github.com/heroku/heroku-bouncer/blob/master/lib/heroku/bouncer/builder.rb#L25-L33).

**Comment by raul** [comment]
Makes sense to me, thanks!
