### ISSUE TITLE
unauthorized user is redirected to /auth/heroku on local server

### ISSUE THREAD

**Issue by timsatterfield** [heroku/heroku-bouncer#59]
Am I missing something?  I would expect to be redirected to a heroku server, and THEN be redirected back to my own service after a valid auth.

No where does this middleware implement /auth/heroku (different than /auth/heroku/callback).

Is this something that needs to be implemented in my own service?  If so I do not see documentation to this effect.

here's my middleware config
```
config.middleware.use ::Heroku::Bouncer,
        oauth: {
          id: ENV['ADMIN_OAUTH_ID'],
          secret: ENV['ADMIN_OAUTH_SECRET']
        },
        secret: ENV['ADMIN_COOKIE_SECRET'],
        expose_token: true
```

**Comment by wuputah** [comment]
`/auth/heroku` is implemented by `omniauth-heroku`, which is added as part of this middleware.
https://github.com/heroku/heroku-bouncer/blob/master/lib/heroku/bouncer/builder.rb#L7-L17

**Comment by timsatterfield** [comment]
Thanks for the quick reply wuputah! So I should not have to do any extra config re: omniauth-heroku ?  Just asking since I do not see this in my routes list.  The code snippet you linked to seems like it should just work automagically?

**Comment by wuputah** [comment]
It is configured for you - nothing you need to do.

**Comment by timsatterfield** [comment]
Okay, then I am really lost, as I consistently get:
```
Started GET "/admin/" for 192.168.1.85 at 2017-10-23 20:08:34 +0000
Started GET "/auth/heroku" for 192.168.1.85 at 2017-10-23 20:08:34 +0000

ActionController::RoutingError (No route matches [GET] "/auth/heroku"):
```
omniauth-heroku (0.3.0)
heroku-bouncer (0.8.0)
rails 4.2.8
ruby 2.4.1

**Comment by wuputah** [comment]
Are you sure your `ENV` keys are set? Are you seeing any `[warn]` or `[fatal]` messages? These are printed to STDERR.

**Comment by timsatterfield** [comment]
No unfortunately  nothing seems to be amiss with ENV keys...  I will spin up a fresh barebones rails project and see what happens. Perhaps there is a hidden conflict with another gem/middleware in my work project.

**Comment by timsatterfield** [comment]
Confirmed a fresh install works as advertised. Perhaps I am seeing a conflict with another gem. Will close this for now.

**Comment by timsatterfield** [comment]
As a note to anyone who hits this problem where both heroku-bouncer and devise_token_auth gems are installed.  DTA sets its own default omniauth prefix, of `/omniauth` where heroku-bouncer expects it to be at `/auth`

To work around this, you can override DTA config to match the expected prefix. This might not be possible if you already have a hard dependency on the default DTA omniauth prefix.
```
# config/initalizers/devise_token_auth.rb
...
config.omniauth_prefix = "/auth"
...

```

**Comment by wuputah** [comment]
Ah, thanks for figuring this out and reporting back. Bouncer should probably look at this setting when creating its routes, etc.
